name: discdiff
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - cuda-nvcc=12.4.99
  - ipykernel=6.29.5
  - ipython=8.15.0
  - ipywidgets=8.1.2
  - pip=23.3.1
  - python=3.9.20
  - pip:
      - biopython==1.84
      - causal-conv1d==1.4.0
      - datasets==2.18.0
      - einops==0.8.0
      - flash-attn==2.7.2.post1
      - fsspec==2024.2.0
      - git-lfs==1.6
      - h5py==3.10.0
      - huggingface-hub==0.26.2
      - hydra-core==1.3.2
      - ipdb==0.13.13
      - jupyter==1.1.1
      - jupyterlab==4.1.8
      - lightning==2.2.1
      - lightning-utilities==0.11.9
      - mamba-ssm==1.2.0.post1
      - matplotlib==3.9.2
      - notebook==7.1.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - pandas==2.2.1
      - pytorch-image-generation-metrics==0.6.1
      - rdkit==2024.3.6
      - regex==2024.11.6
      - rich==13.7.1
      - safetensors==0.4.5
      - scikit-learn==1.4.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - timm==0.9.16
      - tokenizers==0.15.2
      - torch==2.2.2
      - torchmetrics==1.6.0
      - torchvision==0.17.2
      - tqdm==4.67.0
      - transformers==4.38.2
      - triton==2.2.0
      - wandb==0.13.5
